// Angular/myapp/src/app/login/login.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-login',
  imports: [],
  templateUrl: './login.component.html',
  styleUrl: './login.component.css'
})
export class LoginComponent {
    name: string = '';
    password: string = '';
  
    onSubmit() {
      console.log('Name:', this.name);
      console.log('Password:', this.password);
    }
  }

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>login</title>
</head>
<body>
    <form>
        <label>Name:</label>
        <input type="text" placeholder="Enter the name" name="name" required><br>
    
        <label>Password:</label>
        <input type="password" placeholder="Enter your password" name="password" required><br>
    
        <button type="submit">Submit</button>
    </form>
    <a href="/myfies">Go to next page</a>

</body>
</html>

// React/myapp/src/components/login/Login.jsx
import React from "react";

import "./login.css"; 


const Login = () => {
    return (
        <div className='container'>
            <div className="header">
                <div className="text">Signup</div>
            </div>
            <form>
            <div className="forms">
                <div className="label">NAME</div>
                <input type="text"placeholder="name" required/>
                <div className="label">PASSWORD</div>
                <input type="number"placeholder="password" required/>
                <div className="label">AGE</div>
                <input type="number"placeholder="age" required/>
                <button type="submit">Submit</button>
            </div>
            </form>
        </div>
    );
}

export default Login;
