// Angular/myapp/src/app/login/login.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-login',
  imports: [],
  templateUrl: './login.component.html',
  styleUrl: './login.component.css'
})
export class LoginComponent {
    name: string = '';
    password: string = '';
  
    onSubmit() {
      console.log('Name:', this.name);
      console.log('Password:', this.password);
    }
  }

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>login</title>
</head>
<body>
    <form>
        <label>Name:</label>
        <input type="text" placeholder="Enter the name" name="name" required><br>
    
        <label>Password:</label>
        <input type="password" placeholder="Enter your password" name="password" required><br>
    
        <button type="submit">Submit</button>
    </form>
    <a href="/myfies">Go to next page</a>

</body>
</html>

// React/myapp/src/components/Login.jsx
import React from "react";
import "./login.css";
import { useState } from "react";

function Login() {
    const [name, setname] = useState("");
    const [pwd, setpwd] = useState("");

    function handle(event) {
        setname(event.target.value);
    }

    function handles(event) {
        setpwd(event.target.value);
        console.log(name, pwd)
    }
    return (
        <div className="container">
            <div className="header">
                <div className="text">Login</div>
            </div>
            <form>
                <div className="forms">
                    <label htmlFor="name" className="label">Name</label>
                    <input type="text" value={name} onChange={handle} id="name" placeholder="Enter your name" required />

                    <label htmlFor="password" className="label">Password</label>
                    <input type="password" value={pwd} onChange={handles} id="password" placeholder="Enter your password" required />

                    <button type="submit" className="submit-btn">Submit</button>

                    <p>
                        Don't have an account? <a href="/">Sign up</a>
                    </p>
                </div>
            </form>
        </div>
    );
}


export default Login;
